SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

FPS = 75

DEV_MODE = True

MOSQUITO_SIZE = (100, 100)
MOSQUITO_HITBOX_SCALER = [0.5, 1.5]
MOSQUITO_IMAGE_PATH = "mosquito.png"
MOSQUITO_MOVE_SPEED = {"min": 8, "max": 17}
MOSQUITO_SPAWN_PERIOD = 1200  # in ms
MOSQUITO_SPAWN_MARGIN = 40

HAND_OPEN_PATH = "open.png"
HAND_CLOSED_PATH = "closed.png"
HAND_SIZE = (150, 250)
HAND_TRACK_PERIOD = 120
